@startuml


实体 <|-- 空间
实体 <|-- 设备


' 计量表 <|-- 水表
' 计量表 <|-- 电表
' 计量表 <|-- 燃气表
' 计量表 <|-- 冷热量表

' 传感器 <|-- 压力传感器
' 传感器 <|-- 温度传感器

' 控制器 <|-- 空调控制器
' 控制器 <|-- 灯控制器



空间 "1" *-- "0..1" 空间 : > 包含
空间 "1" o-- "0..n" 设备 : < 部署于


设备  <|--  边缘设备 
设备  <|--  计量设备
设备  <|--  受管设备

' 空间 <|-- 园区
' 空间 <|-- 区域
' 空间 <|-- 楼栋
' 空间 <|-- 楼层
' 空间 <|-- 房间

受管设备 <|-- 组合设备

组合设备 "0..1" o-- "1..n" 受管设备 : > 包含


边缘设备 <|-- 传感器
边缘设备 <|-- 控制器
边缘设备 <|-- 网关
计量设备 <|-- 计量表

计量表 <|-- 虚拟计量表

虚拟计量表 *-- 计算规则


虚拟计量表 "1" o-- "1..n" 计量表 : > 包含


计量表 "1" -- "1..n" 受管设备 : > 计量
控制器 .. 受管设备 : > 控制
传感器 .. 受管设备 : > 采集
网关 .. 控制器 : > 命令传输
网关 .. 传感器 : < 数据传输
网关 .. 计量表 : < 数据传输

@enduml