@startuml

实体 <|-- 空间
实体 <|-- 运维设备

空间 "1" *-- "0..1" 空间 : > 包含
空间 "1" o-- "0..n" 运维设备 : < 部署于


运维设备  <|--  计量设备
运维设备  <|--  受管设备
运维设备 <|-- 控制器
运维设备 <|-- 网关

计量设备 <|-- 计量表
计量设备 <|-- 传感器


控制器 .. 受管设备 : > 控制
计量设备 .. 受管设备 : > 采集
网关 .. 控制器 : > 命令传输
网关 .. 计量设备 : < 数据传输

' 设备 <|-- 非耗运维设备

' 受管设备 "1" -- "0..1" 能耗属性
受管设备  <|--  能耗设备
运维设备<|-- 组合设备


组合设备 "0..1" o-- "1..n" 运维设备  : > 包含

class 属性{
    String name
    Object value
}

class 度量{
    String name
    URI measurements
}

class 耗{
    String name
    TSS timespan
    Formula formula
}


class 度量值{
    String name
    TS timestamp
    KV[] measurements
}

实体 "1" *-- "*" 属性 : > 包含

计量设备 "1" *-- 计量点位 : > 包含

度量 "1" -- "1" 计量点位 : < 对应

受管设备 "1" *-- "*" 度量 : > collects

能耗设备 "1" *-- "*" 耗 : > is billed by

度量 "1" -- "*" 度量值 : > refers to

耗 "1" -- "*" 度量 : > caculates on

@enduml